[tool.poetry]
name = "scanapi"
version = "2.9.0"
description = "Automated Testing and Documentation for your REST API"
authors = ["The ScanAPI Organization <cmaiacd@gmail.com>"]
license = "MIT"
readme = "README.md"

repository = "https://github.com/scanapi/scanapi"
homepage = "https://scanapi.dev/"
keywords = ["python", "scanapi", "tests", "end2end", "endtoend", "integration tests", "json", "apis", "api rest"]

[tool.poetry.scripts]
scanapi = "scanapi:main"

[tool.poetry.dependencies]
python = ">=3.7.13,<4.0.0"
appdirs = "^1.4.4"
curlify2 = "^1.0.1"
MarkupSafe = "2.1.2"
rich = "13.3.5"
PyYAML = "6.0.1"
Jinja2 = "~3.1.0"
click = "8.0.3"
httpx = "^0.24.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.3.1"
pytest-cov = "4.0.0"
pytest-freezegun = "0.4.2"
pytest-mock = "3.2.0"
black = "22.3.0"
sphinx = "4.3.2"
sphinx_rtd_theme = ">=0.5,<1.3"
pre-commit = { version = "3.3.1", python = ">=3.8" }
isort = "^5.11.5"
bandit = "^1.6.2"
pytest-it = "^0.1.4"
flake8 = "5.0.4"
mypy = "^0.960"
types-requests = "^2.25.1"
types-PyYAML = "~6.0.0"
types-setuptools = ">=67.7,<69.0"
gitlint = "0.18.0"
requests-mock = "1.10.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts="--it"

[build-system]
requires = ["poetry>=1.0.9",  "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
